#!/usr/bin/env python
import os
import sys
import logging
import optparse
from darkimporter.darkdaemon import Daemon
from darkimporter.libimporter import monitor_buildqueue
from darkimporter.libimporter import create_rundir

logging.basicConfig(filename='/var/log/darkserver.log', level=logging.INFO,\
                        format='%(asctime)s:%(name)s:%(levelname)s:%(message)s')


class DarkDaemon(Daemon):
    def run(self):
        """
        The daemon process
        """
        monitor_buildqueue()


if __name__ == '__main__':
    daemon = None
    create_rundir()
    parser = optparse.OptionParser("usage: %prog [options]")
    parser.add_option("-s","--start",dest="start",
                      action="store_true",help="start the buildqueue")
    parser.add_option("-p","--pid",dest="pid",
                      help="specify the pid for build queue")
    (options,args) = parser.parse_args()
    if options.start is None:
        parser.error("Incorrect number of arguments")
    if options.pid is None:
        parser.error("Argument should contain a PID")
    daemon = DarkDaemon('/var/run/darkserver/darkbuildqueue%s.pid' % pid)
    daemon.start()
    sys.exit(0)
