#!/usr/bin/env python
import os
import sys
import time
import logging
import optparse

import darkimporter.utils as utils
from darkimporter.darkdaemon import Daemon
from darkimporter.libimporter import do_buildid_import, check_shutdown
from darkimporter.libimporter import create_rundir, log_status
from darkimporter.libimporter import remove_redis_keys, get_redis_config, get_key
from darkimporter.utils import log
from retask.queue import Queue
from retask.task import Task

logging.basicConfig(filename='/var/log/darkserver.log', level=logging.INFO,\
                        format='%(asctime)s:%(name)s:%(levelname)s:%(message)s')


class DarkDaemon(Daemon):
    def run(self):
        """
        The daemon process
        """
        key = get_key('darkjobworker')
        config = get_redis_config()
        jobqueue = Queue('jobqueue', config)
        jobqueue.connect()
        log_status('darkjobworker', 'Starting worker module')
        while True:
            if check_shutdown():
                break
            if jobqueue.length == 0:
                log(key, "Sleeping, no jobqueue job", 'info')
                time.sleep(60)
                continue
            try:
                task = jobqueue.dequeue()
                if not task:
                    continue
                url = task.data['url']
                idx = task.data['jobid']
                path = task.data['config_path']
                utils.msgtext = task.data['url']
                log(key, "Import started %s" % idx, 'info')
                do_buildid_import(url, idx, key, path)
                log(key, "Import finished %s" % idx, 'info')
            except Exception, err:
                log(key, str(err), 'error')
        remove_redis_keys('darkjobworker')

if __name__ == '__main__':
    daemon = None
    create_rundir()
    parser = optparse.OptionParser("usage: %prog [options]")
    parser.add_option("-s","--start",dest="start",
                     action="store_true", help="start the buildqueue")
    parser.add_option("-e","--stop",dest="stop",
                     action="store_true", help="stop the buildqueue")
    parser.add_option("-p","--pid",dest="pid",
                    help="specify the pid")
    (options,args) = parser.parse_args()
    if options.start is None and options.stop is None:
        parser.error("Incorrect number of arguments")
    if options.pid is None:
        parser.error("Argument should contain --pid option")
    daemon = DarkDaemon('/var/run/darkserver/darkjobqueue%s.pid' % options.pid)
    if options.stop:
        daemon.stop()
    elif options.start:
        daemon.start()
