#!/usr/bin/env python
import os
import sys
import koji
import logging
import optparse
from darkimporter.darkdaemon import Daemon
from darkimporter.libimporter import produce_jobs
from darkimporter.libimporter import create_rundir

logging.basicConfig(filename='/var/log/darkserver.log', level=logging.INFO,\
                        format='%(asctime)s:%(name)s:%(levelname)s:%(message)s')


class DarkDaemon(Daemon):
    def run(self):
        """
        The daemon process
        """
        config = options.config
        build_id = options.build_id
        if os.path.exists(config_path):
            produce_jobs(int(sys.argv[2]), path=config_path)
        else:
            print 'Invalid Path'


if __name__ == '__main__':
    daemon = None
    create_rundir()
    parser = optparse.OptionParser("usage: %prog [options] args [options] FILE")
    parser.add_option("-s", "--start", dest="build_id",
                        type="string", help="specify the build id")
    parser.add_option("-c", "--config", dest="config",
                        default="/etc/darkserver/config/darkserverurl-koji.conf",
                        type="string", help="specify the config file")
    (options, args) = parser.parse_args()
    if options.build_id is None:
        parser.error("Incorrect number of arguments")
    daemon = DarkDaemon('/var/run/darkserver/darkproducer.pid')
    daemon.start()
