#!/usr/bin/env python
import os
import sys
import koji
import logging
from darkimporter.darkdaemon import Daemon
from darkimporter.libimporter import produce_jobs
from darkimporter.libimporter import create_rundir

logging.basicConfig(filename='/var/log/darkserver.log', level=logging.INFO,\
                        format='%(asctime)s:%(name)s:%(levelname)s:%(message)s')


class DarkDaemon(Daemon):
    def run(self):
        """
        The daemon process
        """
        if len(sys.argv) >= 4:
            if sys.argv[3].startswith('--config='):
                config_path = sys.argv[3].split('--config=')[1]
                if os.path.exists(config_path):
                    produce_jobs(int(sys.argv[2]), path=config_path)
                else:
                    print 'Invalid Path'
            else:
                print 'Unknown command'
                sys.exit(2)
            sys.exit(0)
        else:
            produce_jobs(int(sys.argv[2]))


if __name__ == '__main__':
    daemon = None 
    create_rundir()
    if len(sys.argv) >= 2:
        daemon = DarkDaemon('/var/run/darkserver/darkproducer.pid')

        if 'start' == sys.argv[1]:
            daemon.start()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    else:
        print "usage: %s start" % sys.argv[0]
        sys.exit(2)
